# Application config file.
[development]
port = "8080"
reconnecturl = "http://172.22.203.68/ConvergenceIBSTVG/ICC/reconnectproduct"
disconnecturl = "http://172.22.203.68/ConvergenceIBSTVG/ICC/disconnectproduct"
cancelurl = "http://172.22.203.68/ConvergenceIBSTVG/ICC/cancelproduct"


[production]
port = "8080"
reconnecturl = "http://172.22.203.68/ConvergenceIBSTVG/ICC/reconnectproduct"
disconnecturl = "http://172.22.203.68/ConvergenceIBSTVG/ICC/disconnectproduct"
cancelurl = "http://172.22.203.68/ConvergenceIBSTVG/ICC/cancelproduct"
